name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Needed to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Pull latest changes
      run: |
        git pull origin main --rebase

    - name: Commit and push changes if any
      run: |
        git add cycle_stats.csv
        if [ -f last_update.txt ]; then
          git add last_update.txt
        fi
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m 'Update cycle stats'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
