name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Needed to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Check if CSV file exists
      run: ls -l cycle_stats.csv

    - name: Display CSV file content
      run: cat cycle_stats.csv

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Stash unstaged changes
      run: git stash || echo "No changes to stash"

    - name: Pull latest changes
      run: git pull origin main --rebase

    - name: Apply stashed changes
      if: ${{ steps.stash.outputs.stashed }}
      run: git stash pop || echo "No stashed changes to apply"

    - name: Force add and commit changes
      run: |
        git add -f cycle_stats.csv last_update.txt
        git commit -m 'Update cycle stats' || echo "No changes to commit"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
