name: Update cycle stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Pull latest changes
      run: |
        git pull origin main --rebase

    - name: Commit and push changes if any
      run: |
        git add cycle_stats.csv last_update.txt
        git commit -m "Update cycle stats" || exit 0
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
