name: Python application

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write  # Needed to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run main.py script
      run: python main.py
      
    - name: Commit and push if it changed
      run: |
        git config user.name "TreeCityWes"
        git config user.email "wes@treecitytrading.us"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        timestamp=$(date -u)
        git commit -m "Data updated on ${timestamp}" || exit 0
        git pull --rebase origin main
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/TreeCityWes/QTool.git HEAD:main

    - name: Debug: Confirm commit
      run: git log -1
