name: Update Cycle Data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Needed to push changes to the repository

jobs:
  update-cycle-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Check if CSV files exist
      run: ls -l cycle_stats.csv current_cycle.csv

    - name: Display CSV files content
      run: |
        echo "cycle_stats.csv:"
        cat cycle_stats.csv
        echo "current_cycle.csv:"
        cat current_cycle.csv

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Pull latest changes
      run: |
        git fetch origin main
        git reset --hard origin/main

    - name: Add and commit changes
      run: |
        git add cycle_stats.csv last_update.txt current_cycle.csv
        git commit -m 'Update cycle stats' || echo "No changes to commit"

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
